version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install Prereqs
          command: sudo apt-get update && sudo apt-get install -y yarn
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: |
            if ./.circleci/check_npm_version.sh; then
                yarn publish --access public
            fi

workflows:
  version: 2
  test-publish:
    jobs:
      - publish:
          context: api_keys
          filters:
            branches:
              only:
                - master
